FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

# Встановлюємо залежності
RUN npm install

# Копіюємо всі файли
COPY . .

# Генеруємо Prisma Client перед запуском
RUN npx prisma generate

EXPOSE 3000

# Запускаємо сервер в режимі розробки з hot-reload
CMD ["npm", "run", "start:dev"]
